apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-server
  labels:
    app: prediction-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3

  template:
    metadata:
      labels:
        app: prediction-server
    spec:
      containers:
        - name: prediction-server
          image: prediction-server:stand-alone
          env:
          - name: RUN_ID
            value: "2f5413151de34a28941f3f0dfe028661"
          - name: AWS_DEFAULT_REGION
            value: "ap-south-1"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: mlflow-data
              mountPath: /app/mlflow/

      volumes:
        - name: mlflow-data
          hostPath:
            path: /home/saurav/Documents/Branding/mlops-4/pipeline/data/mlflow
