FROM public.ecr.aws/lambda/python:3.8

#ENV ROOT_PATH_MODEL='/app/mlflow/'
#ENV RUN_ID='2f5413151de34a28941f3f0dfe028661'

#RUN echo "The ROOT_PATH_MODEL path is $ROOT_PATH_MODEL"
RUN echo "The MLFlow RUN_ID is $RUN_ID"

# Install python packages
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

# copy model
COPY mlruns/ mlruns/

COPY [ "lambda_function.py", "./" ]

CMD [ "lambda_function.lambda_handler" ]
