apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  labels:
    app: prefect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: prefect-server
    spec:
      containers:
        - name: prefect-server:v1
          image: prefect-server:v1
          envFrom:
            - configMapRef:
                name: prefect-configmap
            - secretRef:
                name: prefect-secret
